title: Đặng Hải Lộc
description: Website cá nhân của tôi
author: Đặng Hải Lộc
logo: /assets/avatar.png
github: https://github.com/hailoc12
about: Freelance animator

baseurl: "hailocpkb.github.io"
url: "http://hailocpkb.github.io"

allowsearch: true

disqus_shortname: hailocpkb
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
